apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appService.name}}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.appName }}
