apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appService.name}}
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.appName }}
