apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appService.name}}
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Values.appName }}
