appName: challenge-app
appImage:
  name: ogechik/challenge
  tag: latest
appService:
  name: challenge-app-backend
dbName: challenge-db
dbImage:
  name: ogechik/challenge_db
  tag: latest
appHost: a31cdeffe1774422aa75527b6c876e09-1317232858.eu-west-3.elb.amazonaws.com
